using UnityEngine;
using TMPro;
using System.Collections;
using System.Collections.Generic;
using Fusion.XR.Shared.Rig;

public class SharkNPCInteraction : MonoBehaviour
{
    [Header("NPC Settings")]
    public string npcName = "Researcher Alex";
    public bool isAlex = true; // True for Alex, False for Captain

    [Header("UI Styling")]
    public Color backgroundColor = new Color(0f, 0f, 0f, 0.65f); // Beautiful semi-transparent glass style
    public Color textColor = Color.white;

    private AudioSource audioSource;
    private Animator animator;
    private GameObject interactionCanvas;
    private GameObject slideCanvas;
    private TextMeshProUGUI slideTitleText;
    private TextMeshProUGUI slideBodyText;
    private bool playerInside = false;
    private bool isSpeaking = false;
    private Coroutine slideCoroutine;

    [System.Serializable]
    public class Slide
    {
        public string title;
        [TextArea(3, 5)]
        public string text;
        public float duration;

        public Slide(string t, string tx, float dur)
        {
            title = t;
            text = tx;
            duration = dur;
        }
    }

    private List<Slide> slides = new List<Slide>();

    private void Awake()
    {
        audioSource = GetComponent<AudioSource>();
        animator = GetComponent<Animator>();

        // Ensure collider is a trigger
        Collider col = GetComponent<Collider>();
        if (col != null)
        {
            col.isTrigger = true;
        }

        // Initialize Slides
        InitializeSlides();

        // Create the canvases programmatically so it works 100% cleanly without scene dependencies
        CreateInteractionCanvas();
        CreateSlideCanvas();
    }

    private void InitializeSlides()
    {
        if (isAlex)
        {
            slides.Add(new Slide("Introduction to the Great White Shark", "The Great White Shark (Carcharodon carcharias) is one of the most powerful and fascinating marine predators on our planet.", 25f));
            slides.Add(new Slide("Anatomy & Size", "They can grow up to 20 feet (6 meters) in length and weigh over 5,000 pounds (2.2 tonnes). Their fusiform bodies are optimized for high-speed swimming.", 25f));
            slides.Add(new Slide("Super Senses", "They possess an extraordinary sense of smell and the ability to detect electromagnetic fields generated by living prey using their Ampullae of Lorenzini.", 25f));
            slides.Add(new Slide("Hunting & Breaching", "Known for spectacular breach attacks, Great Whites swim extremely fast from the deep below, launching themselves into the air to catch seals.", 25f));
            slides.Add(new Slide("Global Migration Paths", "These sharks are migratory champions, traveling thousands of miles across oceans from California to Hawaii, and South Africa to Australia.", 30f));
            slides.Add(new Slide("Conservation Status", "Great White Sharks are currently classified as Vulnerable. They face critical threats from overfishing, plastic pollution, and marine habitat loss.", 30f));
            slides.Add(new Slide("Their Ecological Role", "As apex predators, they keep the marine ecosystem in balance by regulating seal and sea lion populations, maintaining oceanic health.", 30f));
            slides.Add(new Slide("Coexistence & Respect", "Understanding these creatures helps us co-exist with them. They are not mindless monsters, but essential guardians of our oceans.", 30f));
        }
        else
        {
            slides.Add(new Slide("Welcome Aboard!", "Welcome to our marine research vessel! I'm the Captain, and we are sailing deep into white shark territory today.", 25f));
            slides.Add(new Slide("Vessel Operations", "Operating a research vessel in open waters requires precise coordination, advanced satellite navigation, and strict maritime safety protocols.", 25f));
            slides.Add(new Slide("Locating Great Whites", "We use specialized high-frequency sonar, thermal scanners, and acoustic tracking devices to safely locate feeding grounds without disturbing the sharks.", 25f));
            slides.Add(new Slide("Research Safety Cage", "For underwater scientific research, we deploy heavy-duty galvanized steel cages to keep marine biologists safe during close-up photography and tissue sampling.", 25f));
            slides.Add(new Slide("Tagging & Satellite Tracking", "Our scientific team attaches satellite (SPOT) and acoustic tags to the sharks' dorsal fins to track their migration routes in real-time.", 30f));
            slides.Add(new Slide("Sailing & Sea Weather", "Weather changes rapidly at sea. We constantly monitor oceanic swell heights, wind velocity, and barometric pressure to ensure safe diving operations.", 30f));
            slides.Add(new Slide("Marine Conservation Laws", "We work in partnership with global conservation authorities to enforce marine protected zones and strictly combat illegal shark finning.", 30f));
            slides.Add(new Slide("Protecting Our Blue Planet", "Every drop of the ocean counts. By supporting marine research, we help preserve these waters and their incredible inhabitants for generations to come.", 30f));
        }
    }

    private void CreateInteractionCanvas()
    {
        GameObject canvasObj = new GameObject("TalkInteractionCanvas");
        canvasObj.transform.SetParent(transform);
        canvasObj.transform.localPosition = new Vector3(0f, 1.8f, 0.8f);
        canvasObj.transform.localRotation = Quaternion.identity;
        canvasObj.transform.localScale = new Vector3(0.0018f, 0.0018f, 0.0018f);

        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.WorldSpace;
        canvasObj.AddComponent<UnityEngine.UI.CanvasScaler>();
        canvasObj.AddComponent<UnityEngine.UI.GraphicRaycaster>();

        // Background Panel
        GameObject bgObj = new GameObject("Background");
        bgObj.transform.SetParent(canvasObj.transform, false);
        RectTransform bgRect = bgObj.AddComponent<RectTransform>();
        bgRect.anchorMin = Vector2.zero;
        bgRect.anchorMax = Vector2.one;
        bgRect.sizeDelta = new Vector2(140f, 40f);

        UnityEngine.UI.Image bgImg = bgObj.AddComponent<UnityEngine.UI.Image>();
        bgImg.color = backgroundColor;

        // Button/Text
        GameObject textObj = new GameObject("Label");
        textObj.transform.SetParent(bgObj.transform, false);
        RectTransform textRect = textObj.AddComponent<RectTransform>();
        textRect.anchorMin = Vector2.zero;
        textRect.anchorMax = Vector2.one;
        textRect.sizeDelta = Vector2.zero;

        TextMeshProUGUI text = textObj.AddComponent<TextMeshProUGUI>();
        text.text = $"E / Click to Talk to\n{npcName}";
        text.fontSize = 10f;
        text.alignment = TextAlignmentOptions.Center;
        text.color = textColor;

        // Add a world space button component to handle WebXR controller clicks
        UnityEngine.UI.Button btn = bgObj.AddComponent<UnityEngine.UI.Button>();
        btn.onClick.AddListener(Interact);

        interactionCanvas = canvasObj;
        interactionCanvas.SetActive(false);
    }

    private void CreateSlideCanvas()
    {
        GameObject canvasObj = new GameObject("NPCSlideCanvas");
        canvasObj.transform.SetParent(transform);
        // Position it on the left side of the NPC
        canvasObj.transform.localPosition = new Vector3(-1.3f, 1.6f, 0.6f);
        canvasObj.transform.localRotation = Quaternion.Euler(0f, 35f, 0f);
        canvasObj.transform.localScale = new Vector3(0.007f, 0.007f, 0.007f);

        Canvas canvas = canvasObj.AddComponent<Canvas>();
        canvas.renderMode = RenderMode.WorldSpace;
        canvasObj.AddComponent<UnityEngine.UI.CanvasScaler>();
        canvasObj.AddComponent<UnityEngine.UI.GraphicRaycaster>();

        // Background Panel
        GameObject bgObj = new GameObject("Background");
        bgObj.transform.SetParent(canvasObj.transform, false);
        RectTransform bgRect = bgObj.AddComponent<RectTransform>();
        bgRect.sizeDelta = new Vector2(220f, 130f);

        UnityEngine.UI.Image bgImg = bgObj.AddComponent<UnityEngine.UI.Image>();
        bgImg.color = backgroundColor;

        // Title Text
        GameObject titleObj = new GameObject("Title");
        titleObj.transform.SetParent(bgObj.transform, false);
        RectTransform titleRect = titleObj.AddComponent<RectTransform>();
        titleRect.anchorMin = new Vector2(0f, 0.8f);
        titleRect.anchorMax = new Vector2(1f, 1f);
        titleRect.anchoredPosition = new Vector2(0f, -5f);
        titleRect.sizeDelta = new Vector2(-10f, 0f);

        slideTitleText = titleObj.AddComponent<TextMeshProUGUI>();
        slideTitleText.text = "Educational Program";
        slideTitleText.fontSize = 11f;
        slideTitleText.fontStyle = FontStyles.Bold;
        slideTitleText.alignment = TextAlignmentOptions.Center;
        slideTitleText.color = new Color(0.35f, 0.75f, 1.0f, 1f); // Beautiful light blue title

        // Body Text
        GameObject bodyObj = new GameObject("BodyText");
        bodyObj.transform.SetParent(bgObj.transform, false);
        RectTransform bodyRect = bodyObj.AddComponent<RectTransform>();
        bodyRect.anchorMin = new Vector2(0f, 0f);
        bodyRect.anchorMax = new Vector2(1f, 0.75f);
        bodyRect.anchoredPosition = new Vector2(0f, 5f);
        bodyRect.sizeDelta = new Vector2(-16f, -10f);

        slideBodyText = bodyObj.AddComponent<TextMeshProUGUI>();
        slideBodyText.text = "Initializing...";
        slideBodyText.fontSize = 8.5f;
        slideBodyText.alignment = TextAlignmentOptions.TopLeft;
        slideBodyText.color = textColor;

        slideCanvas = canvasObj;
        slideCanvas.SetActive(false);
    }

    private void Update()
    {
        // Face the camera dynamically so it behaves as a clean billboard in WebXR
        Camera mainCam = Camera.main;
        if (mainCam != null)
        {
            if (interactionCanvas != null && interactionCanvas.activeSelf)
            {
                interactionCanvas.transform.rotation = Quaternion.LookRotation(interactionCanvas.transform.position - mainCam.transform.position);
            }
        }

        // Keyboard E key support for desktop WebXR users
        if (playerInside && interactionCanvas != null && interactionCanvas.activeSelf && !isSpeaking)
        {
#if ENABLE_INPUT_SYSTEM
            if (UnityEngine.InputSystem.Keyboard.current != null && UnityEngine.InputSystem.Keyboard.current.eKey.wasPressedThisFrame)
            {
                Interact();
            }
#else
            if (Input.GetKeyDown(KeyCode.E))
            {
                Interact();
            }
#endif
        }
    }

    private void Interact()
    {
        if (isSpeaking) return;

        Debug.Log($"[SharkNPCInteraction] Interaction started with {npcName}");
        isSpeaking = true;

        if (interactionCanvas != null)
        {
            interactionCanvas.SetActive(false);
        }

        if (slideCanvas != null)
        {
            slideCanvas.SetActive(true);
        }

        // Play audio
        if (audioSource != null && audioSource.clip != null)
        {
            audioSource.Play();
        }

        // Trigger Talking Animation
        if (animator != null)
        {
            animator.SetBool("Talking", true);
        }

        // Start Slide Show coroutine
        if (slideCoroutine != null) StopCoroutine(slideCoroutine);
        slideCoroutine = StartCoroutine(PlaySlideshow());
    }

    private IEnumerator PlaySlideshow()
    {
        for (int i = 0; i < slides.Count; i++)
        {
            if (slideTitleText != null && slideBodyText != null)
            {
                slideTitleText.text = slides[i].title;
                slideBodyText.text = slides[i].text;
            }

            yield return new WaitForSeconds(slides[i].duration);
        }

        // Program finished
        ResetNPC();
    }

    private void ResetNPC()
    {
        isSpeaking = false;
        
        if (audioSource != null)
        {
            audioSource.Stop();
        }

        if (animator != null)
        {
            animator.SetBool("Talking", false);
        }

        if (slideCanvas != null)
        {
            slideCanvas.SetActive(false);
        }

        if (slideCoroutine != null)
        {
            StopCoroutine(slideCoroutine);
            slideCoroutine = null;
        }

        if (playerInside && interactionCanvas != null)
        {
            interactionCanvas.SetActive(true);
        }
    }

    private void OnTriggerEnter(Collider other)
    {
        // Detect local player rig
        HardwareRig rig = other.GetComponentInParent<HardwareRig>();
        if (rig != null || other.CompareTag("Player") || other.name.Contains("Rig") || other.name.Contains("Controller"))
        {
            playerInside = true;
            if (interactionCanvas != null && !isSpeaking)
            {
                interactionCanvas.SetActive(true);
            }
        }
    }

    private void OnTriggerExit(Collider other)
    {
        HardwareRig rig = other.GetComponentInParent<HardwareRig>();
        if (rig != null || other.CompareTag("Player") || other.name.Contains("Rig") || other.name.Contains("Controller"))
        {
            playerInside = false;
            ResetNPC();
            
            if (interactionCanvas != null)
            {
                interactionCanvas.SetActive(false);
            }
        }
    }
}
